### ISSUE TITLE
Uncaught Error: connect ENETDOWN 54.173.38.135:9090 - Local (10.0.0.3:49616)

### ISSUE THREAD

**Issue by gct-faisal** [magalhas/atom-jenkins#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [jenkins](https://github.com/magalhas/atom-jenkins) package, v0.3.5
### Stack Trace

Uncaught Error: connect ENETDOWN 54.173.38.135:9090 - Local (10.0.0.3:49616)

```
At events.js:141

Error: connect ENETDOWN 54.173.38.135:9090 - Local (10.0.0.3:49616)
  at Object.exports._errnoException (util.js:814:11)
  at exports._exceptionWithHostPort (util.js:837:20)
  at connect (net.js:835:14)
  at lookupAndConnect (net.js:928:5)
  at Socket.connect (net.js:897:5)
  at Agent.exports.connect.exports.createConnection (net.js:62:35)
  at Agent.createSocket (_http_agent.js:177:16)
  at Agent.addRequest (_http_agent.js:147:23)
  at new ClientRequest (_http_client.js:133:16)
  at Object.exports.request (http.js:30:10)
  at new Request (/Users/fhumayun/.atom/packages/jenkins/node_modules/restler/lib/restler.js:75:24)
  at request (/Users/fhumayun/.atom/packages/jenkins/node_modules/restler/lib/restler.js:319:17)
  at Object.get (/Users/fhumayun/.atom/packages/jenkins/node_modules/restler/lib/restler.js:326:9)
  at _get (/Users/fhumayun/.atom/packages/jenkins/lib/jenkins-gateway.coffee:16:8)
  at Object.module.exports.getFailingBuilds (/Users/fhumayun/.atom/packages/jenkins/lib/jenkins-gateway.coffee:35:5)
  at JenkinsView.module.exports.JenkinsView.updateStatusBar (/Users/fhumayun/.atom/packages/jenkins/lib/jenkins-view.coffee:42:20)
  at /Users/fhumayun/.atom/packages/jenkins/lib/jenkins-view.coffee:65:32

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db"
    ],
    "disabledPackages": [
      "numbers-on-a-pane",
      "file-type-icons",
      "minimap-color-highlight",
      "remember-session",
      "close-after-last-tab",
      "bower-install",
      "git-grep"
    ],
    "themes": [
      "isotope-ui",
      "no-caffeine-syntax"
    ]
  },
  "jenkins": {
    "url": "http://54.173.38.135:9090",
    "password": "careteam",
    "username": "gct"
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-beautify, v0.28.14
atom-yamljson, v0.2.3
atomatigit, v1.5.4
circle-ci, v0.10.1
color-picker, v2.0.13
color-tabs, v0.1.8
colorful-json, v1.0.0
copy-filename, v1.0.1
css-color-underline, v1.0.1
cucumber, v0.5.0
file-icon-supplement, v0.8.3
file-icons, v1.6.10
file-watcher, v0.4.0
fonts, v0.6.1
git-diff-details, v0.20.0
git-log, v0.4.1
goto-last-edit, v0.2.2
isotope-ui, v2.5.2
javascript-snippets, v1.0.0
jenkins, v0.3.5
language-diff, v0.3.1
language-gherkin, v1.0.3
language-gherkin-pt, v1.0.1
language-groovy-cloned-from-java, v0.3.0
language-puppet, v0.14.0
linter, v1.8.1
linter-javac, v1.2.0
linter-js-yaml, v1.1.2
linter-puppet, v1.0.0
minimap, v4.13.4
no-caffeine-syntax, v0.16.1
tab-numbers, v0.3.0
terminal-panel, v1.14.1
tool-bar, v0.1.9
travis-ci-status, v0.18.0
tree-view-breadcrumb, v0.7.0
tree-view-git-projects, v0.5.0
tree-view-git-status, v0.2.2
tualo-git-context, v0.6.16
webbox-color, v0.5.8

# Dev
No dev packages
```

**Comment by asimqt** [comment]
Any update on this issue?

**Comment by gct-faisal** [comment]
Absolutely none - so I gave up years ago
